#!/usr/bin/env bash
# prepare-bruno-env.sh — Pull post-deploy values from Terraform and save to scripts/bruno.env.
#
# Share the generated scripts/bruno.env with developers who need to run
# apply-bruno-env.sh without direct AWS access.
#
#   ./scripts/prepare-bruno-env.sh [--environment <env>] [--client-id <id>]
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_NAME="$(basename "$REPO_DIR")"
ENVIRONMENT="dev"
CLIENT_ID=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --environment) ENVIRONMENT="$2"; shift 2 ;;
    --client-id)   CLIENT_ID="$2";   shift 2 ;;
    *) echo "Unknown argument: $1 (did you mean --environment?)" >&2; exit 1 ;;
  esac
done
TF_DIR="$REPO_DIR/terraform"
BRUNO_ENV_FILE="$SCRIPT_DIR/bruno.env"

if [[ ! -d "$TF_DIR" ]]; then
  echo "ERROR: terraform directory not found: $TF_DIR" >&2
  echo "       Run this script from the repo root." >&2
  exit 1
fi

if [[ -z "$CLIENT_ID" ]]; then
  read -rp "Consumer client ID (Bruno): " CLIENT_ID
fi
if [[ -z "$CLIENT_ID" ]]; then
  echo "ERROR: consumer client ID is required." >&2
  exit 1
fi

echo ""
echo "=== Reading Terraform outputs ($ENVIRONMENT) ==="
echo ""

echo "Initialising Terraform backend..."
terraform -chdir="$TF_DIR" init \
  -backend-config="key=$REPO_NAME/$ENVIRONMENT/terraform.tfstate" \
  -input=false -no-color >/dev/null

NLB_HOSTNAME=$(terraform -chdir="$TF_DIR" output -raw nlb_hostname 2>/dev/null || true)

if [[ -z "$NLB_HOSTNAME" ]]; then
  echo "ERROR: could not read nlb_hostname from Terraform output." >&2
  echo "       Has the pipeline run successfully at least once?" >&2
  exit 1
fi

# Prefer the custom domain endpoint when one is configured.
MTLS_ENDPOINT=$(terraform -chdir="$TF_DIR" output -raw mtls_endpoint 2>/dev/null || true)
if [[ -n "$MTLS_ENDPOINT" && "$MTLS_ENDPOINT" != "null" ]]; then
  BASE_URL="$MTLS_ENDPOINT"
  CERT_DOMAIN="${MTLS_ENDPOINT#https://}"
else
  BASE_URL="https://${NLB_HOSTNAME}"
  CERT_DOMAIN="$NLB_HOSTNAME"
fi

echo "    nlb_hostname = $NLB_HOSTNAME"
[[ -n "$MTLS_ENDPOINT" && "$MTLS_ENDPOINT" != "null" ]] && echo "    mtls_endpoint = $MTLS_ENDPOINT"
echo "    base_url     = $BASE_URL"
echo "    client_id    = $CLIENT_ID"

cat > "$BRUNO_ENV_FILE" <<EOF
# Generated by prepare-bruno-env.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Share with developers so they can run apply-bruno-env.sh without AWS access.
# DO NOT commit to git.
NLB_HOSTNAME=$NLB_HOSTNAME
BASE_URL=$BASE_URL
CERT_DOMAIN=$CERT_DOMAIN
CLIENT_ID=$CLIENT_ID
EOF

echo ""
echo "Written: $BRUNO_ENV_FILE"
echo ""
"$SCRIPT_DIR/apply-bruno-env.sh"
echo ""
echo "To onboard new developers without AWS access, share scripts/bruno.env —"
echo "they can run ./scripts/apply-bruno-env.sh to configure Bruno locally."
