#!/usr/bin/env bash
# prepare-bruno-env.sh — Configure Bruno for the shared proxy endpoint.
#
# Now that all APIs share a single endpoint (<environment>.api.smartpropdata.org.uk),
# there is no per-API Terraform output to read. Just supply the client ID
# and optionally override the host for non-dev environments.
#
#   ./scripts/prepare-bruno-env.sh [--environment <env>] [--host <hostname>] [--client-id <id>]
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENVIRONMENT="dev"
HOST=""
CLIENT_ID=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --environment) ENVIRONMENT="$2"; shift 2 ;;
    --host)        HOST="$2";        shift 2 ;;
    --client-id)   CLIENT_ID="$2";   shift 2 ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

# Default host is <environment>.api.smartpropdata.org.uk
if [[ -z "$HOST" ]]; then
  HOST="${ENVIRONMENT}.api.smartpropdata.org.uk"
fi

if [[ -z "$CLIENT_ID" ]]; then
  read -rp "Consumer client ID (Bruno): " CLIENT_ID
fi
if [[ -z "$CLIENT_ID" ]]; then
  echo "ERROR: consumer client ID is required." >&2
  exit 1
fi

BRUNO_ENV_FILE="$SCRIPT_DIR/bruno.env"

cat > "$BRUNO_ENV_FILE" <<EOF
# Generated by prepare-bruno-env.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Share with developers so they can run apply-bruno-env.sh without AWS access.
# DO NOT commit to git.
NLB_HOSTNAME=${HOST}
CLIENT_ID=${CLIENT_ID}
EOF

echo ""
echo "Written: $BRUNO_ENV_FILE"
echo "    host     = $HOST"
echo "    clientId = $CLIENT_ID"
echo ""
"$SCRIPT_DIR/apply-bruno-env.sh"
