using System.Net;
using Microsoft.AspNetCore.Mvc.Testing;
using Xunit;

namespace MyApi.Tests;

public class FapiMiddlewareTests(WebApplicationFactory<Program> factory) : IClassFixture<WebApplicationFactory<Program>>
{
    private const string FapiHeader = "x-fapi-interaction-id";
    private const string ValidId = "550e8400-e29b-41d4-a716-446655440000";

    [Fact]
    public async Task MissingHeader_IsAutoGenerated()
    {
        var response = await factory.CreateClient().GetAsync("/health");
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        Assert.True(response.Headers.Contains(FapiHeader));
        Assert.True(Guid.TryParse(response.Headers.GetValues(FapiHeader).First(), out _));
    }

    [Fact]
    public async Task ValidHeader_IsEchoedInResponse()
    {
        var request = new HttpRequestMessage(HttpMethod.Get, "/health");
        request.Headers.Add(FapiHeader, ValidId);

        var response = await factory.CreateClient().SendAsync(request);

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        Assert.Equal(ValidId, response.Headers.GetValues(FapiHeader).First());
    }

    [Fact]
    public async Task InvalidHeader_ReturnsBadRequest()
    {
        var request = new HttpRequestMessage(HttpMethod.Get, "/health");
        request.Headers.Add(FapiHeader, "not-a-uuid");

        var response = await factory.CreateClient().SendAsync(request);

        Assert.Equal(HttpStatusCode.BadRequest, response.StatusCode);
    }
}
